-- AlterTable
ALTER TABLE "products" ADD COLUMN IF NOT EXISTS "cest" TEXT;
ALTER TABLE "products" ADD COLUMN IF NOT EXISTS "cfop" TEXT;
ALTER TABLE "products" ADD COLUMN IF NOT EXISTS "csosn" TEXT;
ALTER TABLE "products" ADD COLUMN IF NOT EXISTS "cst_icms" TEXT;
ALTER TABLE "products" ADD COLUMN IF NOT EXISTS "origem" INTEGER DEFAULT 0;
ALTER TABLE "products" ADD COLUMN IF NOT EXISTS "cst_pis" TEXT;
ALTER TABLE "products" ADD COLUMN IF NOT EXISTS "aliquota_pis" DOUBLE PRECISION;
ALTER TABLE "products" ADD COLUMN IF NOT EXISTS "cst_cofins" TEXT;
ALTER TABLE "products" ADD COLUMN IF NOT EXISTS "aliquota_cofins" DOUBLE PRECISION;
